name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          curl
          -X POST
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token <TOKEN>"
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/assignees
          -d '{"assignees":["${{ github.event.sender }}"]}'
