name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          HTTP_RESP_CODE=$(curl -o /dev/null  -w "%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/assignees -d '{"assignees":["${{ github.event.sender.login }}"]}')
          if [[ $HTTP_RESP_CODE != 200 ]]; then
            echo "Add assignees to an PR failed ($HTTP_RESP_CODE)"
            exit 1
          fi
